#----------------------------------------
# GENERAL SETTINGS
#----------------------------------------

# Site title, appears in the browser tab.
title: "Miczał"

# Site description in search engine.
description: "Simple portfolio-showcase Jekyll theme."

# Language settings for html and seo
lang: "en_GB"
iso-lang: "en"

# Production url.
url: "https://themiczal.github.io"

# Part after .com, etc. use / if none.
baseurl: /



#----------------------------------------
# CONTENT VARIABLES
#----------------------------------------

# Appears in first section and footer
owner: "Miczał"

# Navbar links
nav_sites:
  -
    link: "https://www.instagram.com/miczal_/"
    icon: icon-instagram
  -
    link: "https://www.deviantart.com/miczalpl"
    icon: icon-deviantart
  -
    link: "#"
    icon: icon-youtube

# Main content
header: Hi.</br>I'm&nbsp;Miczał
headerParagraph: Art speaks where words are unable to explain.
indexParagraph1: I'm an aspiring graphic designer. I do <a href="#drawings">Drawings</a>, <a href="#conceptart">Concept Art</a>, <a href="#pixelart">Pixel Art</a> and even <a href="#posters">Posters</a>.
indexParagraph2: Nunc sit amet accumsan mauris. Ut luctus leo ut quam rutrum accumsan.

# Carousel images paths
images:
  -
    full: "https://unsplash.it/1024/512?random=1"
    min: "https://unsplash.it/1024/512?random=1"
  -
    full: "https://unsplash.it/1024/512?random=2"
    min: "https://unsplash.it/1024/512?random=2"
  -
    full: "https://unsplash.it/1024/512?random=3"
    min: "https://unsplash.it/1024/512?random=3"

sections:
  -
    title: Drawings
    id: drawings
    paragraph: Ut condimentum eleifend ante, nec iaculis felis venenatis sit amet. Cras ut augue luctus nibh dignissim pharetra.
    images:
      -
        full: "/assets/img/Drawings1_full.png"
        min: "/assets/img/Drawings1_small.png"
      -
        full: "/assets/img/Drawings2_full.png"
        min: "/assets/img/Drawings2_small.png"
      -
        full: "/assets/img/Drawings3_full.png"
        min: "/assets/img/Drawings3_small.png"
      -
        full: "/assets/img/Drawings4_full.png"
        min: "/assets/img/Drawings4_small.png"
      -
        full: "/assets/img/Drawings5_full.png"
        min: "/assets/img/Drawings5_small.png"
      -
        full: "/assets/img/Drawings6_full.png"
        min: "/assets/img/Drawings6_small.png"
      -
        full: "/assets/img/Drawings7_full.png"
        min: "/assets/img/Drawings7_small.png"
  -
    title: Concept Art
    id: conceptart
    paragraph: Ut condimentum eleifend ante, nec iaculis felis venenatis sit amet. Cras ut augue luctus nibh dignissim pharetra.
    images:
      -
        full: "/assets/img/CA1_full.png"
        min: "/assets/img/CA1_small.png"
      -
        full: "/assets/img/CA2_full.png"
        min: "/assets/img/CA2_small.png"
  -
    title: Pixelart
    id: pixelart
    paragraph: Ut condimentum eleifend ante, nec iaculis felis venenatis sit amet. Cras ut augue luctus nibh dignissim pharetra.
    images:
      -
        full: "/assets/img/Pixelart1_full.png"
        min: "/assets/img/Pixelart1_small.png"
      -
        full: "/assets/img/Pixelart2_full.png"
        min: "/assets/img/Pixelart2_small.png"
      -
        full: "/assets/img/Pixelart3_full.png"
        min: "/assets/img/Pixelart3_small.png"
      -
        full: "/assets/img/Pixelart4_full.png"
        min: "/assets/img/Pixelart4_small.png"
      -
        full: "/assets/img/Pixelart5_full.png"
        min: "/assets/img/Pixelart5_small.png"
      -
        full: "/assets/img/Pixelart6_full.png"
        min: "/assets/img/Pixelart6_small.png"
  -
    title: Posters
    id: posters
    paragraph: Ut condimentum eleifend ante, nec iaculis felis venenatis sit amet. Cras ut augue luctus nibh dignissim pharetra.
    images:
      -
        full: "/assets/img/Posters1_full.png"
        min: "/assets/img/Posters1_small.png"
      -
        full: "/assets/img/Posters2_full.png"
        min: "/assets/img/Posters2_small.png"
      -
        full: "/assets/img/Posters3_full.png"
        min: "/assets/img/Posters3_small.png"
      -
        full: "/assets/img/Posters4_full.png"
        min: "/assets/img/Posters4_small.png"
      -
        full: "/assets/img/Posters5_full.png"
        min: "/assets/img/Posters5_small.png"

# Footer content - please edit the _includes/footer.html file.



#----------------------------------------
# JEKYLL SETTINGS
#----------------------------------------

# Takes files from root folder, generates site into ./_site.
source: .
destination: ./_site

# Default variables for pages. Are in use if not overwritten.
defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"

# Excluding dev gem builds from website.
exclude: [vendor]

# Jekyll plugins.
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
