#----------------------------------------
# GENERAL SETTINGS
#----------------------------------------

# Site title, appears in the browser tab.
title: "Miczał"

# Site description in search engine.
description: "Simple portfolio-showcase Jekyll theme."

# Language settings for html and seo
lang: "en_GB"
iso-lang: "en"

# Production url.
url: "https://themiczal.github.io"

# Part after .com, etc. use / if none.
baseurl: /



#----------------------------------------
# CONTENT VARIABLES
#----------------------------------------

# Appears in first section and footer
owner: "Miczał"

# Navbar links
nav_sites:
  -
    link: "https://www.instagram.com/miczal_/"
    icon: icon-instagram
  -
    link: "https://www.deviantart.com/miczalpl"
    icon: icon-deviantart
  -
    link: "#"
    icon: icon-youtube

# Main content
header: Hi.</br>I'm&nbsp;Miczał
headerParagraph: Art speaks where words are unable to explain.
indexParagraph1: I'm an aspiring graphic designer. I do <a href="#drawings">Drawings</a>, <a href="#conceptart">Concept Art</a>, <a href="#pixelart">Pixel Art</a> and even <a href="#logos">Logos</a>.
indexParagraph2: Nunc sit amet accumsan mauris. Ut luctus leo ut quam rutrum accumsan.

# Carousel images paths
images:
  -
    full: "https://unsplash.it/1024/512?random=1"
    min: "https://unsplash.it/1024/512?random=1"
  -
    full: "https://unsplash.it/1024/512?random=2"
    min: "https://unsplash.it/1024/512?random=2"
  -
    full: "https://unsplash.it/1024/512?random=3"
    min: "https://unsplash.it/1024/512?random=3"

sections:
  -
    title: Drawings
    id: drawings
    paragraph: Ut condimentum eleifend ante, nec iaculis felis venenatis sit amet. Cras ut augue luctus nibh dignissim pharetra.
    images: #5
      -
        full: "https://unsplash.it/1024/512?random=4"
        min: "https://unsplash.it/400/200?random=4"
      -
        full: "https://unsplash.it/1024/512?random=5"
        min: "https://unsplash.it/400/200?random=5"
      -
        full: "https://unsplash.it/1024/512?random=6"
        min: "https://unsplash.it/400/200?random=6"
      -
        full: "https://unsplash.it/1024/512?random=7"
        min: "https://unsplash.it/400/200?random=7"
      -
        full: "https://unsplash.it/1024/512?random=8"
        min: "https://unsplash.it/400/200?random=8"
  -
    title: Concept Art
    id: conceptart
    paragraph: Ut condimentum eleifend ante, nec iaculis felis venenatis sit amet. Cras ut augue luctus nibh dignissim pharetra.
    images: #7
      -
        full: "https://unsplash.it/1024/512?random=9"
        min: "https://unsplash.it/400/200?random=9"
      -
        full: "https://unsplash.it/1024/512?random=10"
        min: "https://unsplash.it/400/200?random=10"
      -
        full: "https://unsplash.it/1024/512?random=11"
        min: "https://unsplash.it/400/200?random=11"
      -
        full: "https://unsplash.it/1024/512?random=12"
        min: "https://unsplash.it/400/200?random=12"
      -
        full: "https://unsplash.it/1024/512?random=13"
        min: "https://unsplash.it/400/200?random=13"
      -
        full: "https://unsplash.it/1024/512?random=14"
        min: "https://unsplash.it/400/200?random=14"
      -
        full: "https://unsplash.it/1024/512?random=15"
        min: "https://unsplash.it/400/200?random=15"
  -
    title: Pixelart
    id: pixelart
    paragraph: Ut condimentum eleifend ante, nec iaculis felis venenatis sit amet. Cras ut augue luctus nibh dignissim pharetra.
    images: #5
      -
        full: "https://unsplash.it/1024/512?random=16"
        min: "https://unsplash.it/400/200?random=16"
      -
        full: "https://unsplash.it/1024/512?random=17"
        min: "https://unsplash.it/400/200?random=17"
      -
        full: "https://unsplash.it/1024/512?random=18"
        min: "https://unsplash.it/400/200?random=18"
      -
        full: "https://unsplash.it/1024/512?random=19"
        min: "https://unsplash.it/400/200?random=19"
      -
        full: "https://unsplash.it/1024/512?random=20"
        min: "https://unsplash.it/400/200?random=20"
  -
    title: Logos
    id: logos
    paragraph: Ut condimentum eleifend ante, nec iaculis felis venenatis sit amet. Cras ut augue luctus nibh dignissim pharetra.
    images: #7
      -
        full: "https://unsplash.it/1024/512?random=21"
        min: "https://unsplash.it/400/200?random=21"
      -
        full: "https://unsplash.it/1024/512?random=22"
        min: "https://unsplash.it/400/200?random=22"
      -
        full: "https://unsplash.it/1024/512?random=23"
        min: "https://unsplash.it/400/200?random=23"
      -
        full: "https://unsplash.it/1024/512?random=24"
        min: "https://unsplash.it/400/200?random=24"
      -
        full: "https://unsplash.it/1024/512?random=25"
        min: "https://unsplash.it/400/200?random=25"
      -
        full: "https://unsplash.it/1024/512?random=26"
        min: "https://unsplash.it/400/200?random=26"
      -
        full: "https://unsplash.it/1024/512?random=27"
        min: "https://unsplash.it/400/200?random=27"

# Footer content - please edit the _includes/footer.html file.



#----------------------------------------
# JEKYLL SETTINGS
#----------------------------------------

# Takes files from root folder, generates site into ./_site.
source: .
destination: ./_site

# Default variables for pages. Are in use if not overwritten.
defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"

# Excluding dev gem builds from website.
exclude: [vendor]

# Jekyll plugins.
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
